// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordsMaker.Infrastructure.DAL;

namespace WordsMaker.Infrastructure.DAL.Migrations
{
    [DbContext(typeof(WordsMakerDbContext))]
    [Migration("20231101173738_FirtMigration")]
    partial class FirtMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WordsMaker.Application.DTO.LangDto", b =>
                {
                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Lang");

                    b.ToTable("DictLangs");
                });

            modelBuilder.Entity("WordsMaker.Application.DTO.SufixDto", b =>
                {
                    b.Property<Guid>("SufixId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentLang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SufixType")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SufixId");

                    b.ToTable("DictSufixes");
                });

            modelBuilder.Entity("WordsMaker.Application.DTO.SufixToWordDto", b =>
                {
                    b.Property<Guid>("WordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SufixId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentLang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WordId", "SufixId");

                    b.ToTable("SufixToWord");
                });

            modelBuilder.Entity("WordsMaker.Application.DTO.TranslationDto", b =>
                {
                    b.Property<Guid>("CurrentWordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ForeignWordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CurrentWordId", "ForeignWordId");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("WordsMaker.Application.DTO.WordDto", b =>
                {
                    b.Property<Guid>("WordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Context")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentLang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WordId");

                    b.ToTable("DictWords");
                });
#pragma warning restore 612, 618
        }
    }
}
